apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdig-agent
data:
  dragent.yaml: |
    ### Agent tags
     tags: cluster:Lupo-Sysdig_Test_Cluster,statefulset:yes

    # Sysdig collector address
     collector:  sysdigcloud.lupo.dev.draios.com

     #Collector TCP port
     collector_port: 6443

     #Whether collector accepts ssl
     ssl: true

    # collector certificate validation
     ssl_verify_certificate: false
     #log:
     #  file_priority: debug 
     new_k8s: true
     k8s_cluster_name: installer-test-d1
     #percentiles: [50, 95, 99]
     app_checks_limit: 1000
     #metrics_excess_log: true
     snaplen: 512
     k8s_extra_resources:
      include:
        - services
        - resourcequotas
        - persistentvolumes
        - persistentvolumeclaims
        - horizontalpodautoscalers
     prometheus:
       enabled: true
       interval: 10
       log_errors: true
       max_metrics: 3000
       max_metrics_per_process: 2000
       max_tags_per_metric: 200
       histograms: true
     jmx:
       limit: 3000
     statsd:
       limit: 1000
     app_checks_always_send: true

     resources:
       limits:
         cpu: 6000m
         memory: 5Gi
       requests:
         cpu: 1000m
         memory: 1024Mi
     
     watchdog:
       max_memory_usage_mb: 2048
       max_memory_usage_subprocesses:
         sdchecks: 128
         sdjagent: 256
         mountedfs_reader: 32
         statsite_forwarder: 32
         cointerface: 4096

     security:
       k8s_audit_server_url: 0.0.0.0
       k8s_audit_server_port: 7765
       enabled: true
     commandlines_capture:
       enabled: true
     nmemdump:
       enabled: true
     app_checks:
       - name: elasticsearch
         check_module: elastic
         pattern:
           port: 9200
           comm: java
         conf:
           url: https://localhost:9200
           username: readonly
           password: password
           ssl_verify: false
